---
version: '2'

volumes:
    # Named volumes - these should be external in a production deployment
    mysql_data:
    nextcloud_data:
    nextcloud_themes:

services:

    mysql:
        image: "percona:5.6"
        user: "mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
        volumes:
            - "mysql_data:/var/lib/mysql"
        expose:
            - "3306"

    redis:
        image: "redis:3.2-alpine"
        command: '--save "" --appendonly no'  # Persistency disabled
        user: "redis"
        expose:
          - "6379"

    nextcloud:
        image: "arkivum/nextcloud"
        build: .
        environment:
            ADMIN_USER: "admin"
            ADMIN_PASSWORD: "admin"
            DB_HOST: "mysql"
            DB_NAME: "nextcloud"
            DB_USER: "root"
            DB_PASSWORD: "12345"
            DB_PORT: "3306"
            DB_TYPE: "mysql"
            GID: "1000"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            UID: "1000"
        volumes:
            - "nextcloud_data:/var/lib/nextcloud"
            - "nextcloud_themes:/nextcloud/themes"
        ports:
            - "38888:8888"
        depends_on:
            - "mysql"
            - "redis"
        links:
            - "mysql"
            - "redis"
